### ISSUE TITLE
Using `v-html` with `ChecButton` will not put content inside content container

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#587]
The button has a `button__content` container that it renders to put content inside. If you use `v-html` with the button, it won't render this content container and will instead toss whatever you put in there.

**Comment by kvisca** [comment]
I investigated a way to bind the `v-html` from the parent into the child div and it's not really possible from what I can tell. The `v-html` is working as intended since it's supposed to replace the inners with the HTML provided. I think going forward the best way to handle situations like this is to just bind the `v-html` in a span inside the button. This will allow it to still work with icons and render the `button_content` I've included an example below:

**Implementation:**
```
<chec-button color="secondary" variant="regular">
    <span v-html="<b>Some bold text</b>" />
</chec-button>
```

**Rendered:**
```
<button type="button" class="button button--variant-regular button--color-secondary">
    <span class="button__content">
        <span><b>Some bold text</b></span>
    </span>
</button>
```
This is probably the best and least destructive way to do this.
